print ("Hello World")
print ("Hello again")
print ("I like typing this")
print("This is fun.")
print ("Yay! Printing!")
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this')
#print ("Here is another line")
print ("Seems like hash's create single line comments in python")
